// Generated by scripts/provider-compatibility.mjs. Do not edit.

export const providers = [
  {
    "id": "codex",
    "logo": "codex",
    "name": "Codex",
    "same": "Resume + fork",
    "cross": "App-server import",
    "signal": ">= 0.146.0",
    "tone": "amber",
    "capabilities": {
      "read_index": [
        "linux",
        "macos"
      ],
      "clean_start": [
        "linux",
        "macos"
      ],
      "same_provider_resume": [
        "linux",
        "macos"
      ],
      "cross_provider_import": [
        "linux",
        "macos"
      ]
    },
    "platformEvidence": {
      "linux": [
        "source-ci",
        "installed-token-free"
      ],
      "macos": [
        "source-ci",
        "synthetic-store"
      ],
      "windows": [
        "source-ci",
        "synthetic-store"
      ]
    }
  },
  {
    "id": "claude-code",
    "logo": "claude-code",
    "name": "Claude Code",
    "same": "Resume + fork",
    "cross": "Native session",
    "signal": ">= 2.1.220",
    "tone": "amber",
    "capabilities": {
      "read_index": [
        "linux",
        "macos"
      ],
      "clean_start": [
        "linux",
        "macos"
      ],
      "same_provider_resume": [
        "linux",
        "macos"
      ],
      "cross_provider_import": [
        "linux",
        "macos"
      ]
    },
    "platformEvidence": {
      "linux": [
        "source-ci",
        "installed-token-free"
      ],
      "macos": [
        "source-ci",
        "synthetic-store"
      ],
      "windows": [
        "source-ci",
        "synthetic-store"
      ]
    }
  },
  {
    "id": "opencode",
    "logo": "opencode",
    "name": "OpenCode",
    "same": "Resume + fork",
    "cross": "Official import",
    "signal": "OFFICIAL",
    "tone": "cyan",
    "capabilities": {
      "read_index": [
        "linux",
        "macos"
      ],
      "clean_start": [
        "linux",
        "macos"
      ],
      "same_provider_resume": [
        "linux",
        "macos"
      ],
      "cross_provider_import": [
        "linux",
        "macos"
      ]
    },
    "platformEvidence": {
      "linux": [
        "source-ci",
        "installed-token-free"
      ],
      "macos": [
        "source-ci",
        "synthetic-store"
      ],
      "windows": [
        "source-ci",
        "synthetic-store"
      ]
    }
  },
  {
    "id": "pi",
    "logo": "pi",
    "name": "Pi",
    "same": "Resume + fork",
    "cross": "v3 JSONL",
    "signal": ">= 0.82.0",
    "tone": "amber",
    "capabilities": {
      "read_index": [
        "linux",
        "macos"
      ],
      "clean_start": [
        "linux",
        "macos"
      ],
      "same_provider_resume": [
        "linux",
        "macos"
      ],
      "cross_provider_import": [
        "linux",
        "macos"
      ]
    },
    "platformEvidence": {
      "linux": [
        "source-ci",
        "synthetic-store"
      ],
      "macos": [
        "source-ci",
        "synthetic-store"
      ],
      "windows": [
        "source-ci",
        "synthetic-store"
      ]
    }
  },
  {
    "id": "grok",
    "logo": "grok",
    "name": "Grok",
    "same": "Resume + fork",
    "cross": "ACP import",
    "signal": ">= 0.2.114",
    "tone": "cyan",
    "capabilities": {
      "read_index": [
        "linux",
        "macos"
      ],
      "clean_start": [
        "linux",
        "macos"
      ],
      "same_provider_resume": [
        "linux",
        "macos"
      ],
      "cross_provider_import": [
        "linux",
        "macos"
      ]
    },
    "platformEvidence": {
      "linux": [
        "source-ci",
        "installed-token-free"
      ],
      "macos": [
        "source-ci",
        "synthetic-store"
      ],
      "windows": [
        "source-ci",
        "synthetic-store"
      ]
    }
  },
  {
    "id": "cursor-ide",
    "logo": "cursor",
    "name": "Cursor IDE",
    "same": "Restore chat",
    "cross": "Desktop state",
    "signal": ">= 3.12.17",
    "tone": "amber",
    "capabilities": {
      "read_index": [
        "linux",
        "macos"
      ],
      "clean_start": [],
      "same_provider_resume": [
        "linux",
        "macos"
      ],
      "cross_provider_import": [
        "linux",
        "macos"
      ]
    },
    "platformEvidence": {
      "linux": [
        "source-ci",
        "synthetic-store"
      ],
      "macos": [
        "source-ci",
        "synthetic-store"
      ],
      "windows": [
        "source-ci",
        "synthetic-store"
      ]
    }
  },
  {
    "id": "cursor-agent",
    "logo": "cursor",
    "name": "Cursor Agent",
    "same": "Resume",
    "cross": "Native session",
    "signal": ">= 2026.07.23-e383d2b",
    "tone": "magenta",
    "capabilities": {
      "read_index": [
        "linux",
        "macos"
      ],
      "clean_start": [
        "linux",
        "macos"
      ],
      "same_provider_resume": [
        "linux",
        "macos"
      ],
      "cross_provider_import": [
        "linux",
        "macos"
      ]
    },
    "platformEvidence": {
      "linux": [
        "source-ci",
        "synthetic-store"
      ],
      "macos": [
        "source-ci",
        "synthetic-store"
      ],
      "windows": [
        "source-ci",
        "synthetic-store"
      ]
    }
  },
  {
    "id": "antigravity",
    "logo": "antigravity",
    "name": "Antigravity CLI",
    "same": "Resume",
    "cross": "Linux state import",
    "signal": ">= 1.1.8",
    "tone": "magenta",
    "capabilities": {
      "read_index": [
        "linux",
        "macos"
      ],
      "clean_start": [
        "linux",
        "macos"
      ],
      "same_provider_resume": [
        "linux",
        "macos"
      ],
      "cross_provider_import": [
        "linux"
      ]
    },
    "platformEvidence": {
      "linux": [
        "source-ci",
        "synthetic-store"
      ],
      "macos": [
        "source-ci",
        "synthetic-store"
      ],
      "windows": [
        "source-ci",
        "synthetic-store"
      ]
    }
  },
  {
    "id": "hermes",
    "logo": "hermes",
    "name": "Hermes",
    "same": "Resume + fork",
    "cross": "Official import",
    "signal": ">= 0.19.1",
    "tone": "cyan",
    "capabilities": {
      "read_index": [
        "linux",
        "macos"
      ],
      "clean_start": [
        "linux",
        "macos"
      ],
      "same_provider_resume": [
        "linux",
        "macos"
      ],
      "cross_provider_import": [
        "linux",
        "macos"
      ]
    },
    "platformEvidence": {
      "linux": [
        "source-ci",
        "installed-token-free"
      ],
      "macos": [
        "source-ci",
        "synthetic-store"
      ],
      "windows": [
        "source-ci",
        "synthetic-store"
      ]
    }
  }
] as const;
