// Generated by scripts/provider-compatibility.mjs. Do not edit.

use omnis_ir::Provider;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Capability {
    ReadIndex,
    CleanStart,
    SameProviderResume,
    CrossProviderImport,
}

#[allow(dead_code)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Platform {
    Linux,
    Macos,
    Windows,
}

#[cfg(target_os = "linux")]
pub(crate) const CURRENT_PLATFORM: Option<Platform> = Some(Platform::Linux);
#[cfg(target_os = "macos")]
pub(crate) const CURRENT_PLATFORM: Option<Platform> = Some(Platform::Macos);
#[cfg(target_os = "windows")]
pub(crate) const CURRENT_PLATFORM: Option<Platform> = Some(Platform::Windows);
#[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
pub(crate) const CURRENT_PLATFORM: Option<Platform> = None;

pub(crate) const PROVIDER_PRIORITY: [Provider; 9] = [
    Provider::Codex,
    Provider::Claude,
    Provider::OpenCode,
    Provider::Pi,
    Provider::Grok,
    Provider::CursorIde,
    Provider::CursorCli,
    Provider::Antigravity,
    Provider::Hermes,
];

pub(crate) const fn supports_capability_on(
    provider: Provider,
    capability: Capability,
    platform: Platform,
) -> bool {
    use Capability::{CleanStart, CrossProviderImport, ReadIndex, SameProviderResume};

    #[allow(clippy::match_same_arms)]
    let platform_mask = match (provider, capability) {
        (Provider::Codex, ReadIndex) => 3,
        (Provider::Codex, CleanStart) => 3,
        (Provider::Codex, SameProviderResume) => 3,
        (Provider::Codex, CrossProviderImport) => 3,
        (Provider::Claude, ReadIndex) => 3,
        (Provider::Claude, CleanStart) => 3,
        (Provider::Claude, SameProviderResume) => 3,
        (Provider::Claude, CrossProviderImport) => 3,
        (Provider::OpenCode, ReadIndex) => 3,
        (Provider::OpenCode, CleanStart) => 3,
        (Provider::OpenCode, SameProviderResume) => 3,
        (Provider::OpenCode, CrossProviderImport) => 3,
        (Provider::Pi, ReadIndex) => 3,
        (Provider::Pi, CleanStart) => 3,
        (Provider::Pi, SameProviderResume) => 3,
        (Provider::Pi, CrossProviderImport) => 3,
        (Provider::Grok, ReadIndex) => 3,
        (Provider::Grok, CleanStart) => 3,
        (Provider::Grok, SameProviderResume) => 3,
        (Provider::Grok, CrossProviderImport) => 3,
        (Provider::CursorIde, ReadIndex) => 3,
        (Provider::CursorIde, CleanStart) => 0,
        (Provider::CursorIde, SameProviderResume) => 3,
        (Provider::CursorIde, CrossProviderImport) => 3,
        (Provider::CursorCli, ReadIndex) => 3,
        (Provider::CursorCli, CleanStart) => 3,
        (Provider::CursorCli, SameProviderResume) => 3,
        (Provider::CursorCli, CrossProviderImport) => 3,
        (Provider::Antigravity, ReadIndex) => 3,
        (Provider::Antigravity, CleanStart) => 3,
        (Provider::Antigravity, SameProviderResume) => 3,
        (Provider::Antigravity, CrossProviderImport) => 3,
        (Provider::Hermes, ReadIndex) => 3,
        (Provider::Hermes, CleanStart) => 3,
        (Provider::Hermes, SameProviderResume) => 3,
        (Provider::Hermes, CrossProviderImport) => 3,
        _ => 0,
    };
    let bit = match platform {
        Platform::Linux => 1,
        Platform::Macos => 2,
        Platform::Windows => 4,
    };
    platform_mask & bit != 0
}

pub(crate) const fn supports_capability(provider: Provider, capability: Capability) -> bool {
    match CURRENT_PLATFORM {
        Some(platform) => supports_capability_on(provider, capability, platform),
        None => false,
    }
}

pub(crate) const MINIMUM_CODEX_VERSION: &str = "0.146.0";
pub(crate) const MINIMUM_CLAUDE_VERSION: &str = "2.1.220";
pub(crate) const MINIMUM_PI_VERSION: &str = "0.82.0";
pub(crate) const MINIMUM_GROK_VERSION: &str = "0.2.114";
pub(crate) const MINIMUM_CURSOR_IDE_VERSION: &str = "3.12.17";
pub(crate) const MINIMUM_CURSOR_AGENT_VERSION: &str = "2026.07.23-e383d2b";
pub(crate) const MINIMUM_ANTIGRAVITY_VERSION: &str = "1.1.8";
pub(crate) const MINIMUM_HERMES_VERSION: &str = "0.19.1";
