// Generated by scripts/provider-compatibility.mjs. Do not edit.

pub(crate) const MINIMUM_CLAUDE_VERSION: &str = "2.1.220";
pub(crate) const MINIMUM_CODEX_VERSION: &str = "0.146.0";
pub(crate) const MINIMUM_GROK_VERSION: &str = "0.2.114";
pub(crate) const MINIMUM_HERMES_VERSION: &str = "0.19.1";
pub(crate) const MINIMUM_ANTIGRAVITY_VERSION: &str = "1.1.8";
pub(crate) const MINIMUM_PI_VERSION: &str = "0.82.0";
pub(crate) const MINIMUM_CURSOR_AGENT_VERSION: &str = "2026.07.23-e383d2b";
pub(crate) const MINIMUM_CURSOR_IDE_VERSION: &str = "3.12.17";
