minimumReleaseAge: 4320
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true

overrides:
  nanoid: 3.3.18
  postcss: 8.5.23
  sharp: 0.35.5
  source-map-js: 1.2.2

allowBuilds:
  esbuild: true
